#!/usr/bin/env ansible-playbook

- name: deploy ECS cluster
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: "'env' is required"
    assert:
      that: env is defined

  - name: deploy cluster
    cloudformation:
      region: '{{ aws_region }}'
      stack_name: ecs-cluster-{{ env }}
      template: ../cloudformation/ecs-cluster.yml
      template_parameters:
        Stage: '{{ env }}'
      termination_protection: true
