AWSTemplateFormatVersion: 2010-09-09

Description: ECS Fargate Cluster

Parameters:

  Stage:
    Type: String

Resources:

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
      - FARGATE_SPOT
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      ClusterSettings:
      - Name: containerInsights
        Value: enabled

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:

  ExecutionRoleArn:
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ExecutionRoleArn

  ClusterName:
    Value: !Ref Cluster
    Export:
      Name: !Sub ${AWS::StackName}-ClusterName
